# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import qall_daemon_client.v1.client.protobuf.daemon_runtime_api_v1.daemon_runtime_api_v1_pb2 as daemon__runtime__api__v1__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in daemon_runtime_api_v1_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServiceInfo = channel.unary_unary(
            "/daemon_runtime_api_v1.Api/GetServiceInfo",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=daemon__runtime__api__v1__pb2.DaemonInfo.FromString,
            _registered_method=True,
        )
        self.CreateWorkerEntry = channel.unary_unary(
            "/daemon_runtime_api_v1.Api/CreateWorkerEntry",
            request_serializer=daemon__runtime__api__v1__pb2.CreateWorkerEntryRequest.SerializeToString,
            response_deserializer=daemon__runtime__api__v1__pb2.WorkerEntry.FromString,
            _registered_method=True,
        )
        self.CreateTaskRun = channel.unary_unary(
            "/daemon_runtime_api_v1.Api/CreateTaskRun",
            request_serializer=daemon__runtime__api__v1__pb2.CreateTaskRunRequest.SerializeToString,
            response_deserializer=daemon__runtime__api__v1__pb2.TaskRun.FromString,
            _registered_method=True,
        )
        self.GetTaskRun = channel.unary_unary(
            "/daemon_runtime_api_v1.Api/GetTaskRun",
            request_serializer=daemon__runtime__api__v1__pb2.GetTaskRunRequest.SerializeToString,
            response_deserializer=daemon__runtime__api__v1__pb2.TaskRun.FromString,
            _registered_method=True,
        )
        self.CreateArtifact = channel.unary_unary(
            "/daemon_runtime_api_v1.Api/CreateArtifact",
            request_serializer=daemon__runtime__api__v1__pb2.CreateArtifactRequest.SerializeToString,
            response_deserializer=daemon__runtime__api__v1__pb2.Artifact.FromString,
            _registered_method=True,
        )
        self.DownloadArtifact = channel.unary_unary(
            "/daemon_runtime_api_v1.Api/DownloadArtifact",
            request_serializer=daemon__runtime__api__v1__pb2.DownloadArtifactRequest.SerializeToString,
            response_deserializer=daemon__runtime__api__v1__pb2.ArtifactPayload.FromString,
            _registered_method=True,
        )
        self.ListArtifacts = channel.unary_unary(
            "/daemon_runtime_api_v1.Api/ListArtifacts",
            request_serializer=daemon__runtime__api__v1__pb2.ListArtifactsRequest.SerializeToString,
            response_deserializer=daemon__runtime__api__v1__pb2.ListArtifactsResponse.FromString,
            _registered_method=True,
        )


class ApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServiceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateWorkerEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateTaskRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTaskRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DownloadArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListArtifacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetServiceInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetServiceInfo,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=daemon__runtime__api__v1__pb2.DaemonInfo.SerializeToString,
        ),
        "CreateWorkerEntry": grpc.unary_unary_rpc_method_handler(
            servicer.CreateWorkerEntry,
            request_deserializer=daemon__runtime__api__v1__pb2.CreateWorkerEntryRequest.FromString,
            response_serializer=daemon__runtime__api__v1__pb2.WorkerEntry.SerializeToString,
        ),
        "CreateTaskRun": grpc.unary_unary_rpc_method_handler(
            servicer.CreateTaskRun,
            request_deserializer=daemon__runtime__api__v1__pb2.CreateTaskRunRequest.FromString,
            response_serializer=daemon__runtime__api__v1__pb2.TaskRun.SerializeToString,
        ),
        "GetTaskRun": grpc.unary_unary_rpc_method_handler(
            servicer.GetTaskRun,
            request_deserializer=daemon__runtime__api__v1__pb2.GetTaskRunRequest.FromString,
            response_serializer=daemon__runtime__api__v1__pb2.TaskRun.SerializeToString,
        ),
        "CreateArtifact": grpc.unary_unary_rpc_method_handler(
            servicer.CreateArtifact,
            request_deserializer=daemon__runtime__api__v1__pb2.CreateArtifactRequest.FromString,
            response_serializer=daemon__runtime__api__v1__pb2.Artifact.SerializeToString,
        ),
        "DownloadArtifact": grpc.unary_unary_rpc_method_handler(
            servicer.DownloadArtifact,
            request_deserializer=daemon__runtime__api__v1__pb2.DownloadArtifactRequest.FromString,
            response_serializer=daemon__runtime__api__v1__pb2.ArtifactPayload.SerializeToString,
        ),
        "ListArtifacts": grpc.unary_unary_rpc_method_handler(
            servicer.ListArtifacts,
            request_deserializer=daemon__runtime__api__v1__pb2.ListArtifactsRequest.FromString,
            response_serializer=daemon__runtime__api__v1__pb2.ListArtifactsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "daemon_runtime_api_v1.Api", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "daemon_runtime_api_v1.Api", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class Api(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServiceInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daemon_runtime_api_v1.Api/GetServiceInfo",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            daemon__runtime__api__v1__pb2.DaemonInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateWorkerEntry(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daemon_runtime_api_v1.Api/CreateWorkerEntry",
            daemon__runtime__api__v1__pb2.CreateWorkerEntryRequest.SerializeToString,
            daemon__runtime__api__v1__pb2.WorkerEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateTaskRun(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daemon_runtime_api_v1.Api/CreateTaskRun",
            daemon__runtime__api__v1__pb2.CreateTaskRunRequest.SerializeToString,
            daemon__runtime__api__v1__pb2.TaskRun.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTaskRun(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daemon_runtime_api_v1.Api/GetTaskRun",
            daemon__runtime__api__v1__pb2.GetTaskRunRequest.SerializeToString,
            daemon__runtime__api__v1__pb2.TaskRun.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateArtifact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daemon_runtime_api_v1.Api/CreateArtifact",
            daemon__runtime__api__v1__pb2.CreateArtifactRequest.SerializeToString,
            daemon__runtime__api__v1__pb2.Artifact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DownloadArtifact(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daemon_runtime_api_v1.Api/DownloadArtifact",
            daemon__runtime__api__v1__pb2.DownloadArtifactRequest.SerializeToString,
            daemon__runtime__api__v1__pb2.ArtifactPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListArtifacts(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daemon_runtime_api_v1.Api/ListArtifacts",
            daemon__runtime__api__v1__pb2.ListArtifactsRequest.SerializeToString,
            daemon__runtime__api__v1__pb2.ListArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
