// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: daemon-runtime-api-v1.proto

package daemon_runtime_api_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Api_GetServiceInfo_FullMethodName    = "/daemon_runtime_api_v1.Api/GetServiceInfo"
	Api_CreateWorkerEntry_FullMethodName = "/daemon_runtime_api_v1.Api/CreateWorkerEntry"
	Api_CreateTaskRun_FullMethodName     = "/daemon_runtime_api_v1.Api/CreateTaskRun"
	Api_GetTaskRun_FullMethodName        = "/daemon_runtime_api_v1.Api/GetTaskRun"
	Api_CreateArtifact_FullMethodName    = "/daemon_runtime_api_v1.Api/CreateArtifact"
	Api_DownloadArtifact_FullMethodName  = "/daemon_runtime_api_v1.Api/DownloadArtifact"
	Api_ListArtifacts_FullMethodName     = "/daemon_runtime_api_v1.Api/ListArtifacts"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	GetServiceInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DaemonInfo, error)
	CreateWorkerEntry(ctx context.Context, in *CreateWorkerEntryRequest, opts ...grpc.CallOption) (*WorkerEntry, error)
	CreateTaskRun(ctx context.Context, in *CreateTaskRunRequest, opts ...grpc.CallOption) (*TaskRun, error)
	GetTaskRun(ctx context.Context, in *GetTaskRunRequest, opts ...grpc.CallOption) (*TaskRun, error)
	CreateArtifact(ctx context.Context, in *CreateArtifactRequest, opts ...grpc.CallOption) (*Artifact, error)
	DownloadArtifact(ctx context.Context, in *DownloadArtifactRequest, opts ...grpc.CallOption) (*ArtifactPayload, error)
	ListArtifacts(ctx context.Context, in *ListArtifactsRequest, opts ...grpc.CallOption) (*ListArtifactsResponse, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GetServiceInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DaemonInfo, error) {
	out := new(DaemonInfo)
	err := c.cc.Invoke(ctx, Api_GetServiceInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) CreateWorkerEntry(ctx context.Context, in *CreateWorkerEntryRequest, opts ...grpc.CallOption) (*WorkerEntry, error) {
	out := new(WorkerEntry)
	err := c.cc.Invoke(ctx, Api_CreateWorkerEntry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) CreateTaskRun(ctx context.Context, in *CreateTaskRunRequest, opts ...grpc.CallOption) (*TaskRun, error) {
	out := new(TaskRun)
	err := c.cc.Invoke(ctx, Api_CreateTaskRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetTaskRun(ctx context.Context, in *GetTaskRunRequest, opts ...grpc.CallOption) (*TaskRun, error) {
	out := new(TaskRun)
	err := c.cc.Invoke(ctx, Api_GetTaskRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) CreateArtifact(ctx context.Context, in *CreateArtifactRequest, opts ...grpc.CallOption) (*Artifact, error) {
	out := new(Artifact)
	err := c.cc.Invoke(ctx, Api_CreateArtifact_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) DownloadArtifact(ctx context.Context, in *DownloadArtifactRequest, opts ...grpc.CallOption) (*ArtifactPayload, error) {
	out := new(ArtifactPayload)
	err := c.cc.Invoke(ctx, Api_DownloadArtifact_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ListArtifacts(ctx context.Context, in *ListArtifactsRequest, opts ...grpc.CallOption) (*ListArtifactsResponse, error) {
	out := new(ListArtifactsResponse)
	err := c.cc.Invoke(ctx, Api_ListArtifacts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility
type ApiServer interface {
	GetServiceInfo(context.Context, *emptypb.Empty) (*DaemonInfo, error)
	CreateWorkerEntry(context.Context, *CreateWorkerEntryRequest) (*WorkerEntry, error)
	CreateTaskRun(context.Context, *CreateTaskRunRequest) (*TaskRun, error)
	GetTaskRun(context.Context, *GetTaskRunRequest) (*TaskRun, error)
	CreateArtifact(context.Context, *CreateArtifactRequest) (*Artifact, error)
	DownloadArtifact(context.Context, *DownloadArtifactRequest) (*ArtifactPayload, error)
	ListArtifacts(context.Context, *ListArtifactsRequest) (*ListArtifactsResponse, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (UnimplementedApiServer) GetServiceInfo(context.Context, *emptypb.Empty) (*DaemonInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceInfo not implemented")
}
func (UnimplementedApiServer) CreateWorkerEntry(context.Context, *CreateWorkerEntryRequest) (*WorkerEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkerEntry not implemented")
}
func (UnimplementedApiServer) CreateTaskRun(context.Context, *CreateTaskRunRequest) (*TaskRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTaskRun not implemented")
}
func (UnimplementedApiServer) GetTaskRun(context.Context, *GetTaskRunRequest) (*TaskRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskRun not implemented")
}
func (UnimplementedApiServer) CreateArtifact(context.Context, *CreateArtifactRequest) (*Artifact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArtifact not implemented")
}
func (UnimplementedApiServer) DownloadArtifact(context.Context, *DownloadArtifactRequest) (*ArtifactPayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadArtifact not implemented")
}
func (UnimplementedApiServer) ListArtifacts(context.Context, *ListArtifactsRequest) (*ListArtifactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArtifacts not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetServiceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetServiceInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_CreateWorkerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkerEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).CreateWorkerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_CreateWorkerEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).CreateWorkerEntry(ctx, req.(*CreateWorkerEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_CreateTaskRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).CreateTaskRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_CreateTaskRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).CreateTaskRun(ctx, req.(*CreateTaskRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetTaskRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetTaskRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetTaskRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetTaskRun(ctx, req.(*GetTaskRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_CreateArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).CreateArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_CreateArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).CreateArtifact(ctx, req.(*CreateArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_DownloadArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).DownloadArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_DownloadArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).DownloadArtifact(ctx, req.(*DownloadArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ListArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ListArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_ListArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ListArtifacts(ctx, req.(*ListArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daemon_runtime_api_v1.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceInfo",
			Handler:    _Api_GetServiceInfo_Handler,
		},
		{
			MethodName: "CreateWorkerEntry",
			Handler:    _Api_CreateWorkerEntry_Handler,
		},
		{
			MethodName: "CreateTaskRun",
			Handler:    _Api_CreateTaskRun_Handler,
		},
		{
			MethodName: "GetTaskRun",
			Handler:    _Api_GetTaskRun_Handler,
		},
		{
			MethodName: "CreateArtifact",
			Handler:    _Api_CreateArtifact_Handler,
		},
		{
			MethodName: "DownloadArtifact",
			Handler:    _Api_DownloadArtifact_Handler,
		},
		{
			MethodName: "ListArtifacts",
			Handler:    _Api_ListArtifacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daemon-runtime-api-v1.proto",
}
