// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: daemon-runtime-api-v1.proto

package daemon_runtime_api_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DaemonInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DaemonInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DaemonInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DaemonInfoMultiError, or
// nil if none found.
func (m *DaemonInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *DaemonInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Version

	if len(errors) > 0 {
		return DaemonInfoMultiError(errors)
	}

	return nil
}

// DaemonInfoMultiError is an error wrapping multiple validation errors
// returned by DaemonInfo.ValidateAll() if the designated constraints aren't met.
type DaemonInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DaemonInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DaemonInfoMultiError) AllErrors() []error { return m }

// DaemonInfoValidationError is the validation error returned by
// DaemonInfo.Validate if the designated constraints aren't met.
type DaemonInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DaemonInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DaemonInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DaemonInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DaemonInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DaemonInfoValidationError) ErrorName() string { return "DaemonInfoValidationError" }

// Error satisfies the builtin error interface
func (e DaemonInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDaemonInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DaemonInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DaemonInfoValidationError{}

// Validate checks the field values on CreateWorkerEntryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateWorkerEntryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateWorkerEntryRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateWorkerEntryRequestMultiError, or nil if none found.
func (m *CreateWorkerEntryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateWorkerEntryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WorkerHash

	// no validation rules for WorkerProvider

	// no validation rules for InputFormat

	if len(errors) > 0 {
		return CreateWorkerEntryRequestMultiError(errors)
	}

	return nil
}

// CreateWorkerEntryRequestMultiError is an error wrapping multiple validation
// errors returned by CreateWorkerEntryRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateWorkerEntryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateWorkerEntryRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateWorkerEntryRequestMultiError) AllErrors() []error { return m }

// CreateWorkerEntryRequestValidationError is the validation error returned by
// CreateWorkerEntryRequest.Validate if the designated constraints aren't met.
type CreateWorkerEntryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateWorkerEntryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateWorkerEntryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateWorkerEntryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateWorkerEntryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateWorkerEntryRequestValidationError) ErrorName() string {
	return "CreateWorkerEntryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateWorkerEntryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateWorkerEntryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateWorkerEntryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateWorkerEntryRequestValidationError{}

// Validate checks the field values on CreateResourceAssignmentRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateResourceAssignmentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateResourceAssignmentRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateResourceAssignmentRequestMultiError, or nil if none found.
func (m *CreateResourceAssignmentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateResourceAssignmentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskHash

	// no validation rules for ResourceProvider

	// no validation rules for ResourceName

	if len(errors) > 0 {
		return CreateResourceAssignmentRequestMultiError(errors)
	}

	return nil
}

// CreateResourceAssignmentRequestMultiError is an error wrapping multiple
// validation errors returned by CreateResourceAssignmentRequest.ValidateAll()
// if the designated constraints aren't met.
type CreateResourceAssignmentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateResourceAssignmentRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateResourceAssignmentRequestMultiError) AllErrors() []error { return m }

// CreateResourceAssignmentRequestValidationError is the validation error
// returned by CreateResourceAssignmentRequest.Validate if the designated
// constraints aren't met.
type CreateResourceAssignmentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateResourceAssignmentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateResourceAssignmentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateResourceAssignmentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateResourceAssignmentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateResourceAssignmentRequestValidationError) ErrorName() string {
	return "CreateResourceAssignmentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateResourceAssignmentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateResourceAssignmentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateResourceAssignmentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateResourceAssignmentRequestValidationError{}

// Validate checks the field values on CreateTaskRunRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTaskRunRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTaskRunRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTaskRunRequestMultiError, or nil if none found.
func (m *CreateTaskRunRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTaskRunRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskHash

	// no validation rules for ArtifactHash

	// no validation rules for ProviderCredentials

	if len(errors) > 0 {
		return CreateTaskRunRequestMultiError(errors)
	}

	return nil
}

// CreateTaskRunRequestMultiError is an error wrapping multiple validation
// errors returned by CreateTaskRunRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateTaskRunRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTaskRunRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTaskRunRequestMultiError) AllErrors() []error { return m }

// CreateTaskRunRequestValidationError is the validation error returned by
// CreateTaskRunRequest.Validate if the designated constraints aren't met.
type CreateTaskRunRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTaskRunRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTaskRunRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTaskRunRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTaskRunRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTaskRunRequestValidationError) ErrorName() string {
	return "CreateTaskRunRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTaskRunRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTaskRunRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTaskRunRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTaskRunRequestValidationError{}

// Validate checks the field values on TaskRun with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TaskRun) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TaskRun with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TaskRunMultiError, or nil if none found.
func (m *TaskRun) ValidateAll() error {
	return m.validate(true)
}

func (m *TaskRun) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Status

	if len(errors) > 0 {
		return TaskRunMultiError(errors)
	}

	return nil
}

// TaskRunMultiError is an error wrapping multiple validation errors returned
// by TaskRun.ValidateAll() if the designated constraints aren't met.
type TaskRunMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TaskRunMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TaskRunMultiError) AllErrors() []error { return m }

// TaskRunValidationError is the validation error returned by TaskRun.Validate
// if the designated constraints aren't met.
type TaskRunValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TaskRunValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TaskRunValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TaskRunValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TaskRunValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TaskRunValidationError) ErrorName() string { return "TaskRunValidationError" }

// Error satisfies the builtin error interface
func (e TaskRunValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTaskRun.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TaskRunValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TaskRunValidationError{}

// Validate checks the field values on GetTaskRunRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetTaskRunRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTaskRunRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTaskRunRequestMultiError, or nil if none found.
func (m *GetTaskRunRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTaskRunRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskRunId

	if len(errors) > 0 {
		return GetTaskRunRequestMultiError(errors)
	}

	return nil
}

// GetTaskRunRequestMultiError is an error wrapping multiple validation errors
// returned by GetTaskRunRequest.ValidateAll() if the designated constraints
// aren't met.
type GetTaskRunRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTaskRunRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTaskRunRequestMultiError) AllErrors() []error { return m }

// GetTaskRunRequestValidationError is the validation error returned by
// GetTaskRunRequest.Validate if the designated constraints aren't met.
type GetTaskRunRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTaskRunRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTaskRunRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTaskRunRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTaskRunRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTaskRunRequestValidationError) ErrorName() string {
	return "GetTaskRunRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTaskRunRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTaskRunRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTaskRunRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTaskRunRequestValidationError{}

// Validate checks the field values on CreateArtifactRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateArtifactRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateArtifactRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateArtifactRequestMultiError, or nil if none found.
func (m *CreateArtifactRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateArtifactRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskRunId

	// no validation rules for Payload

	if len(errors) > 0 {
		return CreateArtifactRequestMultiError(errors)
	}

	return nil
}

// CreateArtifactRequestMultiError is an error wrapping multiple validation
// errors returned by CreateArtifactRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateArtifactRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateArtifactRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateArtifactRequestMultiError) AllErrors() []error { return m }

// CreateArtifactRequestValidationError is the validation error returned by
// CreateArtifactRequest.Validate if the designated constraints aren't met.
type CreateArtifactRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateArtifactRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateArtifactRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateArtifactRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateArtifactRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateArtifactRequestValidationError) ErrorName() string {
	return "CreateArtifactRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateArtifactRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateArtifactRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateArtifactRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateArtifactRequestValidationError{}

// Validate checks the field values on ListArtifactsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListArtifactsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListArtifactsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListArtifactsRequestMultiError, or nil if none found.
func (m *ListArtifactsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListArtifactsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskRunId

	if len(errors) > 0 {
		return ListArtifactsRequestMultiError(errors)
	}

	return nil
}

// ListArtifactsRequestMultiError is an error wrapping multiple validation
// errors returned by ListArtifactsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListArtifactsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListArtifactsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListArtifactsRequestMultiError) AllErrors() []error { return m }

// ListArtifactsRequestValidationError is the validation error returned by
// ListArtifactsRequest.Validate if the designated constraints aren't met.
type ListArtifactsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListArtifactsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListArtifactsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListArtifactsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListArtifactsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListArtifactsRequestValidationError) ErrorName() string {
	return "ListArtifactsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListArtifactsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListArtifactsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListArtifactsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListArtifactsRequestValidationError{}

// Validate checks the field values on DownloadArtifactRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DownloadArtifactRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DownloadArtifactRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DownloadArtifactRequestMultiError, or nil if none found.
func (m *DownloadArtifactRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DownloadArtifactRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ArtifactHash

	if len(errors) > 0 {
		return DownloadArtifactRequestMultiError(errors)
	}

	return nil
}

// DownloadArtifactRequestMultiError is an error wrapping multiple validation
// errors returned by DownloadArtifactRequest.ValidateAll() if the designated
// constraints aren't met.
type DownloadArtifactRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DownloadArtifactRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DownloadArtifactRequestMultiError) AllErrors() []error { return m }

// DownloadArtifactRequestValidationError is the validation error returned by
// DownloadArtifactRequest.Validate if the designated constraints aren't met.
type DownloadArtifactRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DownloadArtifactRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DownloadArtifactRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DownloadArtifactRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DownloadArtifactRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DownloadArtifactRequestValidationError) ErrorName() string {
	return "DownloadArtifactRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DownloadArtifactRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDownloadArtifactRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DownloadArtifactRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DownloadArtifactRequestValidationError{}

// Validate checks the field values on Artifact with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Artifact) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Artifact with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ArtifactMultiError, or nil
// if none found.
func (m *Artifact) ValidateAll() error {
	return m.validate(true)
}

func (m *Artifact) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Hash

	if len(errors) > 0 {
		return ArtifactMultiError(errors)
	}

	return nil
}

// ArtifactMultiError is an error wrapping multiple validation errors returned
// by Artifact.ValidateAll() if the designated constraints aren't met.
type ArtifactMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArtifactMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArtifactMultiError) AllErrors() []error { return m }

// ArtifactValidationError is the validation error returned by
// Artifact.Validate if the designated constraints aren't met.
type ArtifactValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArtifactValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArtifactValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArtifactValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArtifactValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArtifactValidationError) ErrorName() string { return "ArtifactValidationError" }

// Error satisfies the builtin error interface
func (e ArtifactValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArtifact.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArtifactValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArtifactValidationError{}

// Validate checks the field values on ArtifactPayload with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ArtifactPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArtifactPayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ArtifactPayloadMultiError, or nil if none found.
func (m *ArtifactPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *ArtifactPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Payload

	if len(errors) > 0 {
		return ArtifactPayloadMultiError(errors)
	}

	return nil
}

// ArtifactPayloadMultiError is an error wrapping multiple validation errors
// returned by ArtifactPayload.ValidateAll() if the designated constraints
// aren't met.
type ArtifactPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArtifactPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArtifactPayloadMultiError) AllErrors() []error { return m }

// ArtifactPayloadValidationError is the validation error returned by
// ArtifactPayload.Validate if the designated constraints aren't met.
type ArtifactPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArtifactPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArtifactPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArtifactPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArtifactPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArtifactPayloadValidationError) ErrorName() string { return "ArtifactPayloadValidationError" }

// Error satisfies the builtin error interface
func (e ArtifactPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArtifactPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArtifactPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArtifactPayloadValidationError{}

// Validate checks the field values on ListArtifactsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListArtifactsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListArtifactsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListArtifactsResponseMultiError, or nil if none found.
func (m *ListArtifactsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListArtifactsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetArtifacts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListArtifactsResponseValidationError{
						field:  fmt.Sprintf("Artifacts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListArtifactsResponseValidationError{
						field:  fmt.Sprintf("Artifacts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListArtifactsResponseValidationError{
					field:  fmt.Sprintf("Artifacts[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListArtifactsResponseMultiError(errors)
	}

	return nil
}

// ListArtifactsResponseMultiError is an error wrapping multiple validation
// errors returned by ListArtifactsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListArtifactsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListArtifactsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListArtifactsResponseMultiError) AllErrors() []error { return m }

// ListArtifactsResponseValidationError is the validation error returned by
// ListArtifactsResponse.Validate if the designated constraints aren't met.
type ListArtifactsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListArtifactsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListArtifactsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListArtifactsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListArtifactsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListArtifactsResponseValidationError) ErrorName() string {
	return "ListArtifactsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListArtifactsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListArtifactsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListArtifactsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListArtifactsResponseValidationError{}

// Validate checks the field values on ResourceAssignment with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResourceAssignment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceAssignment with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResourceAssignmentMultiError, or nil if none found.
func (m *ResourceAssignment) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceAssignment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskHash

	// no validation rules for ResourceProvider

	// no validation rules for ResourceName

	if len(errors) > 0 {
		return ResourceAssignmentMultiError(errors)
	}

	return nil
}

// ResourceAssignmentMultiError is an error wrapping multiple validation errors
// returned by ResourceAssignment.ValidateAll() if the designated constraints
// aren't met.
type ResourceAssignmentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceAssignmentMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceAssignmentMultiError) AllErrors() []error { return m }

// ResourceAssignmentValidationError is the validation error returned by
// ResourceAssignment.Validate if the designated constraints aren't met.
type ResourceAssignmentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceAssignmentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceAssignmentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceAssignmentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceAssignmentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceAssignmentValidationError) ErrorName() string {
	return "ResourceAssignmentValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceAssignmentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceAssignment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceAssignmentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceAssignmentValidationError{}

// Validate checks the field values on WorkerEntry with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WorkerEntry) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WorkerEntry with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WorkerEntryMultiError, or
// nil if none found.
func (m *WorkerEntry) ValidateAll() error {
	return m.validate(true)
}

func (m *WorkerEntry) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for WorkerHash

	// no validation rules for WorkerProvider

	// no validation rules for InputFormat

	if len(errors) > 0 {
		return WorkerEntryMultiError(errors)
	}

	return nil
}

// WorkerEntryMultiError is an error wrapping multiple validation errors
// returned by WorkerEntry.ValidateAll() if the designated constraints aren't met.
type WorkerEntryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WorkerEntryMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WorkerEntryMultiError) AllErrors() []error { return m }

// WorkerEntryValidationError is the validation error returned by
// WorkerEntry.Validate if the designated constraints aren't met.
type WorkerEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WorkerEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WorkerEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WorkerEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WorkerEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WorkerEntryValidationError) ErrorName() string { return "WorkerEntryValidationError" }

// Error satisfies the builtin error interface
func (e WorkerEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWorkerEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WorkerEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WorkerEntryValidationError{}
